trigger:
- none

# no PR triggers
pr: none

pool:
  name: "Default" 
  demands: agent.name -equals bliss-slave-windows2

variables:
  packageName: 'ApiBancoPackage'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  webFolder: "ApiBanco"
  sourcePath: "ApiBanco"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Building project ApiBanco"
    inputs:
      command: "build"
      publishWebProjects: true
      projects: "$(sourcePath)/$(webFolder)/*.csproj"
      arguments: "--configuration $(BuildConfiguration) --version-suffix $(Build.BuildNumber) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Publishing project $(webFolder)"
    inputs:
      command: "publish"
      publishWebProjects: true
      projects: "$(sourcePath)/$(webFolder)/*.csproj"
      arguments: "--configuration $(BuildConfiguration) --version-suffix $(Build.BuildNumber) --no-restore --no-build --output $(Build.ArtifactStagingDirectory)/$(webFolder)"
      zipAfterPublish: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(build.artifactStagingDirectory)/$(webFolder)"
      artifact: "$(packageName)"
      publishLocation: "pipeline"